USE [master]
GO
/****** Object:  Database [AppDBContext]    Script Date: 15.04.2023 21:57:43 ******/
CREATE DATABASE [AppDBContext]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AppDBContext', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AppDBContext.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AppDBContext_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AppDBContext_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AppDBContext] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AppDBContext].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AppDBContext] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AppDBContext] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AppDBContext] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AppDBContext] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AppDBContext] SET ARITHABORT OFF 
GO
ALTER DATABASE [AppDBContext] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AppDBContext] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AppDBContext] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AppDBContext] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AppDBContext] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AppDBContext] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AppDBContext] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AppDBContext] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AppDBContext] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AppDBContext] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AppDBContext] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AppDBContext] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AppDBContext] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AppDBContext] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AppDBContext] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AppDBContext] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [AppDBContext] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AppDBContext] SET RECOVERY FULL 
GO
ALTER DATABASE [AppDBContext] SET  MULTI_USER 
GO
ALTER DATABASE [AppDBContext] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AppDBContext] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AppDBContext] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AppDBContext] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AppDBContext] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AppDBContext] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AppDBContext', N'ON'
GO
ALTER DATABASE [AppDBContext] SET QUERY_STORE = OFF
GO
USE [AppDBContext]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 15.04.2023 21:57:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarrierConfigurations]    Script Date: 15.04.2023 21:57:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarrierConfigurations](
	[CarrierConfigurationId] [int] IDENTITY(1,1) NOT NULL,
	[CarrierId] [int] NOT NULL,
	[CarrierMaxDesi] [int] NOT NULL,
	[CarrierMinDesi] [int] NOT NULL,
	[CarrierCost] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_CarrierConfigurations] PRIMARY KEY CLUSTERED 
(
	[CarrierConfigurationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carriers]    Script Date: 15.04.2023 21:57:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carriers](
	[CarrierId] [int] IDENTITY(1,1) NOT NULL,
	[CarrierName] [nvarchar](max) NOT NULL,
	[CarrierIsActive] [bit] NOT NULL,
	[CarrierPlusDesiCost] [int] NOT NULL,
	[CarrierConfigurationId] [int] NOT NULL,
 CONSTRAINT [PK_Carriers] PRIMARY KEY CLUSTERED 
(
	[CarrierId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 15.04.2023 21:57:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderId] [int] IDENTITY(1,1) NOT NULL,
	[CarrierId] [int] NOT NULL,
	[OrderDesi] [int] NOT NULL,
	[OrderDate] [datetime2](7) NOT NULL,
	[OrderCarrierCost] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_CarrierConfigurations_CarrierId]    Script Date: 15.04.2023 21:57:43 ******/
CREATE NONCLUSTERED INDEX [IX_CarrierConfigurations_CarrierId] ON [dbo].[CarrierConfigurations]
(
	[CarrierId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Orders_CarrierId]    Script Date: 15.04.2023 21:57:43 ******/
CREATE NONCLUSTERED INDEX [IX_Orders_CarrierId] ON [dbo].[Orders]
(
	[CarrierId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarrierConfigurations]  WITH CHECK ADD  CONSTRAINT [FK_CarrierConfigurations_Carriers_CarrierId] FOREIGN KEY([CarrierId])
REFERENCES [dbo].[Carriers] ([CarrierId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CarrierConfigurations] CHECK CONSTRAINT [FK_CarrierConfigurations_Carriers_CarrierId]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Carriers_CarrierId] FOREIGN KEY([CarrierId])
REFERENCES [dbo].[Carriers] ([CarrierId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Carriers_CarrierId]
GO
USE [master]
GO
ALTER DATABASE [AppDBContext] SET  READ_WRITE 
GO
